INSERT INTO user_manager_user (username, password, email, role, department, first_name, last_name, designation, processing_minutes_allowed,processed_minutes,is_active, license_id)
VALUES
('guest1@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest1@gmail.com', 'job_creator', 'Engineering', 'guest', '1', 'User',1000,0,1,1)


INSERT INTO user_manager_user (username, password, email, role, department, first_name, last_name, designation, processing_minutes_allowed,processed_minutes,is_active, license_id)
VALUES
('guest1@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest1@gmail.com', 'report_generator', 'Engineering', 'guest', '1', 'User',1000,0,1,1),
('guest2@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest2@gmail.com', 'report_generator', 'Engineering', 'guest', '2', 'User',1000,0,1,1),
('guest3@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest3@gmail.com', 'report_generator', 'Engineering', 'guest', '3', 'User',1000,0,1,1),
('guest4@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest4@gmail.com', 'report_generator', 'Engineering', 'guest', '4', 'User',1000,0,1,1),
('guest5@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest5@gmail.com', 'report_generator', 'Engineering', 'guest', '5', 'User',1000,0,1,1),
('guest6@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest6@gmail.com', 'report_generator', 'Engineering', 'guest', '6', 'User',1000,0,1,1),
('guest7@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest7@gmail.com', 'report_generator', 'Engineering', 'guest', '7', 'User',1000,0,1,1),
('guest8@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest8@gmail.com', 'report_generator', 'Engineering', 'guest', '8', 'User',1000,0,1,1),
('guest9@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest9@gmail.com', 'report_generator', 'Engineering', 'guest', '9', 'User',1000,0,1,1),
('guest10@gmail.com', 'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=', 'guest10@gmail.com', 'report_generator', 'Engineering', 'guest', '10', 'User',1000,0,1,1);



UPDATE user_manager_user
SET is_active = 1
WHERE username IN (
    'guest1@gmail.com', 'guest2@gmail.com', 'guest3@gmail.com',
    'guest4@gmail.com', 'guest5@gmail.com', 'guest6@gmail.com',
    'guest7@gmail.com', 'guest8@gmail.com', 'guest9@gmail.com',
    'guest10@gmail.com'
);



--Many User Creation Query
-- Delete existing entries with the same email pattern
-- This block removes any existing users with emails that follow the
-- 'guest<number>@gmail.com' pattern to avoid duplicate entries.
DELETE FROM user_manager_user
WHERE email LIKE 'guest%@gmail.com';

-- Recursive Common Table Expression (CTE) to Generate User Data
-- This CTE, named `user_generator`, generates a list of numbers from 1 to 50.
-- Each number represents a unique user ID suffix.
-- `prefix` is set as 'guest' for consistent email and username generation.
WITH RECURSIVE user_generator AS (
    SELECT 1 AS id, 'guest' AS prefix  -- Start with the first user ID
    UNION ALL
    SELECT id + 1, prefix              -- Increment ID by 1 in each recursive step
    FROM user_generator
    WHERE id < 50                      -- Stop recursion when reaching 50 users
)

-- Insert 50 Generated Users into `user_manager_user`
-- This block inserts 50 users generated by the `user_generator` CTE into the
-- `user_manager_user` table. Each user has a unique email and username.
INSERT INTO user_manager_user (
    username, password, email, role, department, first_name, last_name,
    designation, processing_minutes_allowed, processed_minutes, is_active, license_id
)
SELECT
    prefix || id || '@gmail.com' AS username,           -- Generated username in 'guest<number>@gmail.com' format
    'pbkdf2_sha256$600000$tFDsbFfa1crDSWqJEY9zXN$VWRB8lpX1gq0WxXX76G6UR5V3sNXaCOlFr7V0tUBL14=' AS password, -- Encrypted default password
    prefix || id || '@gmail.com' AS email,              -- Generated email in 'guest<number>@gmail.com' format
    'report_creator' AS role,                           -- Set role for each user
    'Engineering' AS department,                        -- Set department for each user
    prefix AS first_name,                               -- Assign 'guest' as the first name
    id AS last_name,                                    -- Use user ID as the last name for uniqueness
    'User' AS designation,                              -- Set a default designation
    1000 AS processing_minutes_allowed,                 -- Set allowed processing minutes
    0 AS processed_minutes,                             -- Initialize processed minutes to 0
    1 AS is_active,                                     -- Set each user as active
    1 AS license_id                                     -- Assign a default license ID
FROM user_generator;
